export type IconName =
    | 'add-circle-line'
    | 'chevron-left'
    | 'cross-mark'
    | 'desktop-screen'
    | 'information-circle'
    | 'minus'
    | 'mobile-screen'
    | 'refresh-arrows'
    | 'save'
    | 'search'
    | 'ui-button-play'
    | 'ui-default'
    | 'ui-eject'
    | 'ui-table-columns'
    | 'ui-toggle-off';
