root: true
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - plugin:react/recommended
    - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaVersion: 'latest'
    ecmaFeatures:
        jsx: true
    sourceType: module
plugins:
    - 'react'
    - '@typescript-eslint'
    - 'prettier'
rules:
    no-shadow: 'off'
    no-use-before-define: 'off'
    'react/prop-types': 'off'
    'react/react-in-jsx-scope': 'off'
    'react/jsx-pascal-case': 'error'
    'react/no-deprecated': 'error'
    '@typescript-eslint/no-shadow': 'error'
    '@typescript-eslint/no-use-before-define': 'off'
    '@typescript-eslint/no-namespace': 'off'
    '@typescript-eslint/no-empty-interface': 'off'
ignorePatterns:
    - '**/*/node_modules'
    - '**/*/dist'
    - '**/*/build'
settings:
    'react':
        'version': 'detect'
