bracketSameLine: true
proseWrap: 'always'
semi: true
singleQuote: true
tabWidth: 4
trailingComma: 'none'
useTabs: false
overrides:
    - files:
          - '*.html'
      options:
          singleQuote: false
