# build stage
FROM node:18-alpine as build-stage
RUN npm install -g pnpm
WORKDIR /frontend
COPY package*.json ./
RUN pnpm install
COPY . .
# RUN cd apps/frontend 
RUN pnpm frontend install
RUN pnpm frontend:build

# production stage
FROM nginx:stable-alpine as production-stage
COPY apps/frontend/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build-stage apps/frontend/dist /usr/share/nginx/html
EXPOSE 80
