name: Publish
on:
    push:
        branches:
            - main
jobs:
    sync:
        name: Sync with deployment repo
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Sync and merge upstream repository with your current repository
                env:
                    UPSTREAM_USER: ${{ secrets.UPSTREAM_USER }}
                    UPSTREAM_REPO_NAME: ${{ secrets.UPSTREAM_REPO_NAME }}
                run: |
                    chmod +x ./.deploy/entrypoint.sh
                    ./.deploy/entrypoint.sh
                shell: bash
                