name: Publish
on:
    merge:
        branches:
            - main
jobs:
    sync:
        name: Sync with deployment repo
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Sync and merge upstream repository with your current repository
              uses: dabreadman/sync-upstream-repo@v1.0.0.b
              with:
                  # URL of gitHub public upstream repo
                  upstream_repo: 'https://github.com/private-frelya-team/react-site-editor.git'
                  # Branch to merge from upstream (defaults to downstream branch)
                  upstream_branch: main
                  # GitHub Bot token
                  token: ${{ secrets.GITHUB_TOKEN }}
