name: Another Deploy
on: pull_request
jobs:
    sync:
        name: Sync with deployment repo
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Sync and merge upstream repository with your current repository
                run: |
                    chmod +x ./deploy/entrypoint.sh
                    ./deploy/entrypoint.sh
                shell: bash
