name: Deployment on prod

on:
  push:
    branches: [ "feat/ci-build" ]
  pull_request:
    branches: [ "feat/ci-build" ]


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: epoundor
        password: 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

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/epoundor/react-site-editor:stagging
        no-cache: true