name: Lint
on: pull_request
jobs:
    eslint:
        name: Lint using ESLint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install modules
              working-directory: .
              run: npm install
            - name: Run ESLint
              working-directory: .
              run: npm eslint --ext .js,.ts,.jsx,.tsx,.json .
